### ISSUE TITLE
Disable interpolation

### ISSUE THREAD

**Issue by silas229** [mthh/loc-i18next#10]
I want to disable interpolation for an element, but the interpolated string is displayed. My code: 
`localize("#myElement", {interpolation: {escapeValue: false}});`

**Comment by mthh** [comment]
I'm not sure that `{interpolation: {escapeValue: false}}` is supposed to disable interpolation but only to toggle off the escaping (regarding i18next documentation on interpolation : https://www.i18next.com/translation-function/interpolation#unescape)
