### ISSUE TITLE
Does this support Internet Explorer?

### ISSUE THREAD

**Issue by tomwayson** [mthh/loc-i18next#13]
I _think_ it does b/c it looks to me like you are using preset-env w/o any target (i.e. no .browserlistrc, no target specified in .babelrc), which looks like it [defaults to ES5](https://babeljs.io/docs/en/babel-preset-env#no-targets).

Is the intent of this project to support Internet Explorer?

We have this requirement b/c we are thinking about using it for the page we will show to IE users when they try to visit our app (which does **not** support IE).

**Comment by YueMiyuki** [comment]
What in the hell IE is already long dead

**Comment by tomwayson** [comment]
so is this issue
