### ISSUE TITLE
Not usable with npm

### ISSUE THREAD

**Issue by kent1D** [mthh/loc-i18next#2]
Hi, actually this plugin can not be used correctly with `require('loc-i18next')`.

The dist folder doesn't exists.

**Comment by kent1D** [comment]
I just added a pull request #3 

It seems to work perfectly for me

**Comment by kent1D** [comment]
And (sorry), thanks a lot for that plugin

**Comment by mthh** [comment]
Thanks for reporting and fixing this !
I will test it and merge it today.
Btw, before I merge and release it, don't hesitate to credit yourself in the `package.json` file if you want.

**Comment by kent1D** [comment]
Don't worry for my name in credits, it doesn't count so much for 3 lines added ;)
