### ISSUE TITLE
Pass a custom document object to the options of handle

### ISSUE THREAD

**Issue by thjungers** [mthh/loc-i18next#21]
Passing a custom `document` object can be useful. My use case is shadow DOMs: the contents of the shadow DOMs are not available to `document.querySelectorAll`, but are available to `shadowRoot.querySelectorAll`.

Although not documented, this plugin accepts a `document` option in `init`, which defaults to `document` (i.e. `window.document`). This was added by commit 6d6569d.
However, this change does not support passing a custom document to the `handle` function. This would allow using a different document object within the same project.

I am preparing a pull request to solve this.

**Comment by mthh** [comment]
That's a good idea, thanks.

I will also add some documentation for the `document` option that can be given to the `init` function, thanks for the reminder.
