### ISSUE TITLE
What if I need the translation on the whole page?

### ISSUE THREAD

**Issue by franva** [mthh/loc-i18next#6]
Hi there,

I have to switch languages on whole page. How do I do it?
What I saw from the document indicates that I have to use a selector to locate where the attribute is,
so if I want to have the translation on the whole page, does it mean that I need to do it like this:

`localize("body");`

Please help.

Thanks

**Comment by mthh** [comment]
If your are using the `localize` function I guess you have filled an attribute with the translation key to use for each element (its `data-i18n` by default). So you can select all the elements of your page having that attribute and have them translated by using `localize('[data-i18n]')` (that is the way I use it when I have to change the language for a whole page)

**Comment by franva** [comment]
thanks @mthh I have tried and it works. Is it possible to retrieve translation from local json files?
e.g. I have chinese.json and english.json under locales folder.

**Comment by mthh** [comment]
Sure! But this is not really a job for `loc-i18next` but rather for [`i18next`](https://github.com/i18next/i18next) and / or one of the other plugins available such as [`i18next-xhr-backend`](https://github.com/i18next/i18next-xhr-backend).
Look at this page of `i18next` documentation that should give you some answers : [i18next documentation - Add or Load Translations](https://www.i18next.com/how-to/add-or-load-translations)
As your original problem seems to be solved i'm gonna close this issue but don't hesitate to open a new one if needed!
