### ISSUE TITLE
Tagged Version

### ISSUE THREAD

**Issue by ipbc-dev** [mthh/loc-i18next#8]
We're using your code in an Firefox Extension and their guidelines ask to link to specific tagged version of third party libraries, if you could add a tag for the latest version we'd appreciate it very much, thank you.

**Comment by mthh** [comment]
I created and pushed a tagged version : https://github.com/mthh/loc-i18next/tree/v0.1.4

**Comment by ipbc-dev** [comment]
Thank you for the quick response.
